apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: trading-env
  labels:
    app.kubernetes.io/name: trading-env
    app.kubernetes.io/part-of: trading
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    name: trading-env
    creationPolicy: Owner
  data:
    - secretKey: DATABENTO_API_KEY
      remoteRef:
        key: philipp-trading-dev-databento-api-key
