apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tradovate-env
  labels:
    app.kubernetes.io/name: htf-sweep-cisd
    app.kubernetes.io/part-of: trading
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    name: tradovate-env
    creationPolicy: Owner
  data:
    - secretKey: TRADOVATE_USERNAME
      remoteRef:
        key: philipp-trading-dev-tradovate-username
    - secretKey: TRADOVATE_PASSWORD
      remoteRef:
        key: philipp-trading-dev-tradovate-password
    - secretKey: TRADOVATE_APP_ID
      remoteRef:
        key: philipp-trading-dev-tradovate-app-id
    - secretKey: TRADOVATE_CID
      remoteRef:
        key: philipp-trading-dev-tradovate-cid
    - secretKey: TRADOVATE_SEC
      remoteRef:
        key: philipp-trading-dev-tradovate-sec
    - secretKey: TRADOVATE_ACCOUNT_ID
      remoteRef:
        key: philipp-trading-dev-tradovate-account-id
