apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: command-and-control
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alloy-log-reader
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: command-and-control
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: alloy-log-reader
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: command-and-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alloy-log-reader
subjects:
  - kind: ServiceAccount
    name: alloy
