apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-strategy-control-auth
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: command-and-control
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    name: grafana-strategy-control-auth
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: philipp-trading-dev-strategy-control-token
