apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: philipp-grafana-admin
  labels:
    app.kubernetes.io/name: philipp-grafana
    app.kubernetes.io/part-of: philipp-command-and-control
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    name: philipp-grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: philipp-trading-dev-grafana-admin-password
