apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tws-login
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: IB_USERNAME
      remoteRef:
        key: philipp-tws-1-username
    - secretKey: IB_PASSWORD
      remoteRef:
        key: philipp-tws-1-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tws-rdp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-gsm
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: RDP_PASSWORD
      remoteRef:
        key: philipp-tws-1-rdp-password
