apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: philipp-trading-dev

resources:
  - ../../../base/strategies
  - control-auth-external-secret.yaml

patches:
  - path: subscribe-deployment.yaml
  - path: htf-sweep-cisd-deployment.yaml
  - path: strategy-control-deployment.yaml

images:
  - name: philipp-trading-dev
    newName: europe-west1-docker.pkg.dev/oned-works/oned/philipp-trading-dev
    newTag: latest
